#!/usr/bin/env bash
set -uo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
PALETTE="$CONFIG_HOME/nbshell/palette.sh"
BRAVE_POLICY="${NBSHELL_BRAVE_POLICY:-/etc/brave/policies/managed/nbshell-color.json}"
IMPORT='@import url("nbshell-theme.css"); /* managed by nbshell */'

die() { printf 'nbshell browser theme: %s\n' "$1" >&2; exit 1; }

palette_value() {
	local key="$1" fallback="$2" value
	value=$(sed -n "s/^${key}=['\"]\([^'\"]*\)['\"]$/\1/p" "$PALETTE" 2>/dev/null | tail -1)
	printf '%s' "${value:-$fallback}"
}

zen_profiles() {
	local root profile
	for root in "$CONFIG_HOME/zen" "$HOME/.zen" "$HOME/.var/app/app.zen_browser.zen/.zen" "$HOME/.var/app/app.zen_browser.zen/zen"; do
		[[ -d $root ]] || continue
		for profile in "$root"/*; do
			[[ -d $profile && -f $profile/prefs.js ]] && printf '%s\n' "$profile"
		done
	done
}

setup_zen() {
	local profile found=0
	while IFS= read -r profile; do
		found=1
		mkdir -p "$profile/chrome"
		grep -qF 'toolkit.legacyUserProfileCustomizations.stylesheets' "$profile/user.js" 2>/dev/null || \
			printf '%s\n' 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$profile/user.js"
		grep -qF 'managed by nbshell' "$profile/chrome/userChrome.css" 2>/dev/null || \
			printf '\n%s\n' "$IMPORT" >> "$profile/chrome/userChrome.css"
	done < <(zen_profiles)
	[[ $found == 1 ]] || die "no Zen profile was found; start Zen once first"
	apply_zen
	printf 'Zen theme integration installed. Restart Zen once.\n'
}

apply_zen() {
	[[ -r $PALETTE ]] || return 0
	local bg surface fg muted accent selection profile
	bg=$(palette_value NB_BG '#1e1e2e')
	surface=$(palette_value NB_BG_LIGHT '#313244')
	fg=$(palette_value NB_FG '#cdd6f4')
	muted=$(palette_value NB_FG_DIM '#7f849c')
	accent=$(palette_value NB_ACCENT '#89b4fa')
	selection=$(palette_value NB_SELECTION "$surface")
	while IFS= read -r profile; do
		[[ -f $profile/chrome/userChrome.css ]] || continue
		grep -qF 'managed by nbshell' "$profile/chrome/userChrome.css" || continue
		cat > "$profile/chrome/nbshell-theme.css" <<EOF
/* Generated by nbshell. Personal rules belong in userChrome.css. */
:root {
  --zen-primary-color: $accent !important;
  --lwt-accent-color: $bg !important;
  --lwt-text-color: $fg !important;
  --toolbar-bgcolor: $bg !important;
  --toolbar-color: $fg !important;
  --toolbar-field-background-color: $surface !important;
  --toolbar-field-color: $fg !important;
  --toolbar-field-focus-background-color: $selection !important;
  --toolbar-field-focus-color: $fg !important;
  --tab-selected-bgcolor: $surface !important;
  --arrowpanel-background: $surface !important;
  --arrowpanel-color: $fg !important;
  --focus-outline-color: $accent !important;
  --button-hover-bgcolor: color-mix(in srgb, $accent 18%, transparent) !important;
  --button-active-bgcolor: color-mix(in srgb, $accent 30%, transparent) !important;
  --sidebar-text-color: $fg !important;
  --sidebar-background-color: $bg !important;
  --zen-colors-border: $muted !important;
}

#navigator-toolbox,
#zen-main-app-wrapper,
#zen-sidebar-top-buttons {
  background-color: $bg !important;
  color: $fg !important;
}
EOF
	done < <(zen_profiles)
}

setup_brave() {
	command -v brave >/dev/null 2>&1 || die "Brave is not installed"
	local owner group temporary
	owner=$(id -un)
	group=$(id -gn)
	temporary=$(mktemp)
	printf '%s\n' '{"BrowserThemeColor":"#1c2027","BrowserColorScheme":"dark"}' > "$temporary"
	sudo install -d -m 0755 /etc/brave/policies/managed
	sudo install -o "$owner" -g "$group" -m 0644 "$temporary" "$BRAVE_POLICY"
	rm -f "$temporary"
	apply_brave
	printf 'Brave theme policy installed.\n'
}

apply_brave() {
	[[ -r $PALETTE && -w $BRAVE_POLICY ]] || return 0
	local accent mode
	accent=$(palette_value NB_ACCENT '#1c2027')
	mode=$(palette_value NB_MODE 'dark')
	# Dark is the safe default. Brave switches to its light chrome only when a
	# theme explicitly declares itself as light.
	[[ $mode == light ]] || mode=dark
	printf '{"BrowserThemeColor":"%s","BrowserColorScheme":"%s"}\n' "$accent" "$mode" > "$BRAVE_POLICY"
	if command -v brave >/dev/null 2>&1 && pgrep -x brave >/dev/null 2>&1; then
		brave --refresh-platform-policy --no-startup-window >/dev/null 2>&1 &
	fi
}

status() {
	local profiles configured=0 profile
	profiles=$(zen_profiles | wc -l)
	while IFS= read -r profile; do
		grep -qF 'managed by nbshell' "$profile/chrome/userChrome.css" 2>/dev/null && configured=$((configured + 1))
	done < <(zen_profiles)
	printf 'Palette   %s\n' "$([[ -r $PALETTE ]] && echo ready || echo missing)"
	printf 'Zen       %s profile(s), %s configured\n' "$profiles" "$configured"
	printf 'Brave     %s\n' "$([[ -w $BRAVE_POLICY ]] && echo configured || echo 'setup required')"
}

case "${1:-status}" in
setup)
	setup_zen
	setup_brave
	;;
setup-zen) setup_zen ;;
setup-brave) setup_brave ;;
apply)
	apply_zen
	apply_brave
	;;
status) status ;;
*) die "usage: browser-theme.sh status|setup|setup-zen|setup-brave|apply" ;;
esac
