#!/usr/bin/env bash
set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
PALETTE="$CONFIG_HOME/nbshell/palette.sh"
BRAVE_POLICY=/etc/brave/policies/managed/nbshell-color.json
BRAVE_HELPER=/usr/lib/nbshell/brave-theme-policy
BRAVE_ACTION=/usr/share/polkit-1/actions/org.nbshell.brave-theme.policy
BRAVE_FLAGS="$CONFIG_HOME/brave-flags.conf"
BRAVE_FLAGS_BEGIN='# nbshell browser theme begin'
BRAVE_FLAGS_END='# nbshell browser theme end'
IMPORT='@import url("nbshell-theme.css"); /* managed by nbshell */'
OMAZEN_COLORS="${NBSHELL_OMAZEN_COLORS:-$CONFIG_HOME/nbshell/omazen-colors.toml}"
OMAZEN_PROGRAM_DIR="${NBSHELL_OMAZEN_PROGRAM_DIR:-/opt/zen-browser-bin}"
OMAZEN_REVISION=1c11bc65c6a5c6d075ecd4019a6ae0ec615cad94
OMAZEN_REPOSITORY=https://github.com/hemagome/omazen.git
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f $SCRIPT_DIR/../integrations/omazen/nbshell-external-provider-arch.patch ]]; then
	OMAZEN_PATCH="$SCRIPT_DIR/../integrations/omazen/nbshell-external-provider-arch.patch"
else
	OMAZEN_PATCH="$SCRIPT_DIR/../../integrations/omazen/nbshell-external-provider-arch.patch"
fi

die() { printf 'nbshell browser theme: %s\n' "$1" >&2; exit 1; }

palette_value() {
	local key="$1" fallback="$2" value
	value=$(sed -n "s/^${key}=['\"]\([^'\"]*\)['\"]$/\1/p" "$PALETTE" 2>/dev/null | tail -1)
	value="${value:-$fallback}"
	if [[ $key != NB_MODE && ! $value =~ ^#[[:xdigit:]]{6}$ ]]; then
		die "invalid palette color for $key"
	fi
	printf '%s' "$value"
}

zen_profiles() {
	local root profile
	for root in "$CONFIG_HOME/zen" "$HOME/.zen" "$HOME/.var/app/app.zen_browser.zen/.zen" "$HOME/.var/app/app.zen_browser.zen/zen"; do
		[[ -d $root ]] || continue
		for profile in "$root"/*; do
			[[ -d $profile && -f $profile/prefs.js ]] && printf '%s\n' "$profile"
		done
	done
}

omazen_binary() {
	command -v omazen 2>/dev/null || {
		[[ -x $HOME/.local/bin/omazen ]] && printf '%s\n' "$HOME/.local/bin/omazen"
	}
}

omazen_configured() {
	local profile
	[[ -f $OMAZEN_PROGRAM_DIR/defaults/pref/omazen-prefs.js ]] || return 1
	while IFS= read -r profile; do
		[[ -f $profile/chrome/JS/omazen-bridge.uc.js ]] && return 0
	done < <(zen_profiles)
	return 1
}

write_omazen_colors() {
	local temporary mode bg dark light fg muted accent selection
	mode=$(palette_value NB_MODE dark)
	[[ $mode == light ]] || mode=dark
	bg=$(palette_value NB_BG '#1e1e2e')
	dark=$(palette_value NB_BG_DARK "$bg")
	light=$(palette_value NB_BG_LIGHT "$bg")
	fg=$(palette_value NB_FG '#cdd6f4')
	muted=$(palette_value NB_FG_DIM '#7f849c')
	accent=$(palette_value NB_ACCENT '#89b4fa')
	selection=$(palette_value NB_SELECTION "$light")
	mkdir -p "$(dirname "$OMAZEN_COLORS")"
	temporary=$(mktemp "$(dirname "$OMAZEN_COLORS")/.omazen-colors.XXXXXX")
	chmod 600 "$temporary"
	cat >"$temporary" <<EOF
# Generated by nbshell for the Zen theme bridge. Do not edit manually.
mode = "$mode"
accent = "$accent"
selection = "$selection"
muted = "$muted"
background = "$bg"
dark_background = "$dark"
darker_background = "$dark"
lighter_background = "$light"
foreground = "$fg"
dark_foreground = "$muted"
EOF
	mv -f "$temporary" "$OMAZEN_COLORS"
}

run_omazen() {
	local binary
	binary=$(omazen_binary) || die "Zen theme bridge is not installed"
	env OMAZEN_ACTIVE_COLORS="$OMAZEN_COLORS" OMAZEN_SKIP_THEME_HOOK=1 "$binary" "$@"
}

remove_legacy_zen_import() {
	local profile css temporary
	while IFS= read -r profile; do
		css="$profile/chrome/userChrome.css"
		[[ -f $css ]] || continue
		grep -qF "$IMPORT" "$css" || continue
		temporary=$(mktemp "$profile/chrome/.userChrome.XXXXXX")
		grep -vF "$IMPORT" "$css" >"$temporary" || true
		chmod --reference="$css" "$temporary"
		mv -f "$temporary" "$css"
	done < <(zen_profiles)
}

setup_zen_live() {
	write_omazen_colors
	run_omazen setup
	run_omazen doctor >/dev/null || die "Omazen setup did not pass its post-install doctor; the restart fallback remains active"
	remove_legacy_zen_import
	printf 'Zen live theme integration installed. Restart Zen once to load the privileged bridge.\n'
}

install_zen_live() (
	command -v git >/dev/null 2>&1 || die "git is required to build Omazen"
	command -v rustup >/dev/null 2>&1 || die "rustup with toolchain 1.98.0 is required to build Omazen"
	[[ -f $OMAZEN_PATCH ]] || die "the nbshell Omazen compatibility patch is missing"
	local stage
	stage=$(mktemp -d "${TMPDIR:-/tmp}/nbshell-omazen.XXXXXX")
	trap 'rm -rf -- "$stage"' EXIT
	git clone --no-checkout "$OMAZEN_REPOSITORY" "$stage/source"
	git -C "$stage/source" checkout --detach "$OMAZEN_REVISION"
	patch -d "$stage/source" -p1 <"$OMAZEN_PATCH"
	cd "$stage/source"
	rustup run 1.98.0 cargo test --locked
	rustup run 1.98.0 cargo build --release --locked
	OMAZEN_BIN="$stage/source/target/release/omazen-rust" tests/test.sh
	OMAZEN_RUST_BINARY="$stage/source/target/release/omazen-rust" \
		OMAZEN_ACTIVE_COLORS="$OMAZEN_COLORS" OMAZEN_SKIP_THEME_HOOK=1 ./install.sh
	printf '%s\n' "Omazen 1.5.0 installed for nbshell's external palette provider. Restart Zen once."
)

doctor_zen_live() {
	write_omazen_colors
	run_omazen doctor
}

setup_zen() {
	local profile found=0
	while IFS= read -r profile; do
		found=1
		mkdir -p "$profile/chrome"
		grep -qF 'toolkit.legacyUserProfileCustomizations.stylesheets' "$profile/user.js" 2>/dev/null || \
			printf '%s\n' 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);' >> "$profile/user.js"
		grep -qF 'managed by nbshell' "$profile/chrome/userChrome.css" 2>/dev/null || \
			printf '\n%s\n' "$IMPORT" >> "$profile/chrome/userChrome.css"
	done < <(zen_profiles)
	[[ $found == 1 ]] || die "no Zen profile was found; start Zen once first"
	apply_zen
	printf 'Zen theme integration installed. Restart Zen once.\n'
}

apply_zen() {
	[[ -r $PALETTE ]] || return 0
	local bg surface fg muted accent selection profile
	bg=$(palette_value NB_BG '#1e1e2e')
	surface=$(palette_value NB_BG_LIGHT '#313244')
	fg=$(palette_value NB_FG '#cdd6f4')
	muted=$(palette_value NB_FG_DIM '#7f849c')
	accent=$(palette_value NB_ACCENT '#89b4fa')
	selection=$(palette_value NB_SELECTION "$surface")
	while IFS= read -r profile; do
		[[ -f $profile/chrome/userChrome.css ]] || continue
		grep -qF 'managed by nbshell' "$profile/chrome/userChrome.css" || continue
		cat > "$profile/chrome/nbshell-theme.css" <<EOF
/* Generated by nbshell. Personal rules belong in userChrome.css. */
:root {
  --zen-primary-color: $accent !important;
  --lwt-accent-color: $bg !important;
  --lwt-text-color: $fg !important;
  --toolbar-bgcolor: $bg !important;
  --toolbar-color: $fg !important;
  --toolbar-field-background-color: $surface !important;
  --toolbar-field-color: $fg !important;
  --toolbar-field-focus-background-color: $selection !important;
  --toolbar-field-focus-color: $fg !important;
  --tab-selected-bgcolor: $surface !important;
  --arrowpanel-background: $surface !important;
  --arrowpanel-color: $fg !important;
  --focus-outline-color: $accent !important;
  --button-hover-bgcolor: color-mix(in srgb, $accent 18%, transparent) !important;
  --button-active-bgcolor: color-mix(in srgb, $accent 30%, transparent) !important;
  --sidebar-text-color: $fg !important;
  --sidebar-background-color: $bg !important;
  --zen-colors-border: $muted !important;
}

#navigator-toolbox,
#zen-main-app-wrapper,
#zen-sidebar-top-buttons {
  background-color: $bg !important;
  color: $fg !important;
}
EOF
	done < <(zen_profiles)
	if omazen_configured; then
		write_omazen_colors
		run_omazen sync >/dev/null || printf 'nbshell browser theme: Zen live sync failed\n' >&2
	fi
}

brave_health() {
	/usr/bin/python3 -I "$SCRIPT_DIR/brave-theme-health.py" 2>/dev/null || printf 'unknown\n'
}

brave_configured() {
	# No implicit authentication or writes through the legacy user-owned policy.
	[[ -x $BRAVE_HELPER && -r $BRAVE_ACTION && -f $BRAVE_POLICY && ! -L $BRAVE_POLICY ]] || return 1
	[[ $(brave_health) == secure ]] || return 1
}

setup_brave() {
	command -v brave >/dev/null 2>&1 || die "Brave is not installed"
	[[ -x /usr/bin/pkexec && -x /usr/bin/sudo ]] || die "polkit and sudo are required"
	/usr/bin/sudo /usr/bin/python3 -I "$SCRIPT_DIR/brave-theme-setup.py"
	brave_configured || die "Brave policy setup verification failed"
	apply_brave
	printf 'Brave theme policy installed.\n'
}

apply_brave_mode() {
	local mode temporary
	mode=$(palette_value NB_MODE 'dark')
	[[ $mode == light ]] || mode=dark
	mkdir -p "$CONFIG_HOME"
	temporary=$(mktemp "$CONFIG_HOME/.brave-flags.XXXXXX")
	if [[ -f $BRAVE_FLAGS ]]; then
		awk -v begin="$BRAVE_FLAGS_BEGIN" -v end="$BRAVE_FLAGS_END" '
			$0 == begin { managed = 1; next }
			$0 == end { managed = 0; next }
			!managed { print }
		' "$BRAVE_FLAGS" > "$temporary"
	fi
	if [[ $mode == dark ]]; then
		[[ ! -s $temporary ]] || printf '\n' >> "$temporary"
		printf '%s\n%s\n%s\n' "$BRAVE_FLAGS_BEGIN" '--force-dark-mode' "$BRAVE_FLAGS_END" >> "$temporary"
	fi
	mv "$temporary" "$BRAVE_FLAGS"
}

apply_brave() {
	[[ -r $PALETTE ]] || return 0
	brave_configured || return 0
	local browser_color mode
	mode=$(palette_value NB_MODE 'dark')
	if [[ $mode == light ]]; then
		browser_color=$(palette_value NB_BG_LIGHT '#f5f5f5')
	else
		# A bright accent creates a light autogenerated Chromium theme even
		# when Brave was started with --force-dark-mode. Seed the browser theme
		# from the actual background so dark palettes remain visibly dark.
		browser_color=$(palette_value NB_BG '#1c2027')
	fi
	[[ $browser_color =~ ^#[[:xdigit:]]{6}$ ]] || die "invalid Brave theme color"
	apply_brave_mode
	/usr/bin/pkexec --disable-internal-agent "$BRAVE_HELPER" "$browser_color" || {
		printf 'nbshell browser theme: Brave policy update denied; apply from an active local session.\n' >&2
		return 0
	}
	if command -v brave >/dev/null 2>&1 && pgrep -x brave >/dev/null 2>&1; then
		brave --refresh-platform-policy --no-startup-window >/dev/null 2>&1 &
	fi
}

status() {
	local profiles configured=0 profile
	profiles=$(zen_profiles | wc -l)
	while IFS= read -r profile; do
		grep -qF 'managed by nbshell' "$profile/chrome/userChrome.css" 2>/dev/null && configured=$((configured + 1))
	done < <(zen_profiles)
	printf 'Palette   %s\n' "$([[ -r $PALETTE ]] && echo ready || echo missing)"
	printf 'Zen CSS   %s profile(s), %s using the restart fallback\n' "$profiles" "$configured"
	printf 'Zen live  %s\n' "$(omazen_configured && echo configured || echo 'setup required')"
	if [[ $(brave_health) == insecure ]]; then
		printf 'Brave     INSECURE policy permissions; run nbshell browser-theme setup-brave\n'
		return 0
	fi
	printf 'Brave     %s (%s mode)\n' "$(brave_configured && echo configured || echo 'setup required')" "$(palette_value NB_MODE dark)"
}

case "${1:-status}" in
setup)
	setup_zen
	setup_brave
	;;
setup-zen) setup_zen ;;
setup-zen-live) setup_zen_live ;;
install-zen-live) install_zen_live ;;
doctor-zen-live) doctor_zen_live ;;
setup-brave) setup_brave ;;
apply)
	apply_zen
	apply_brave
	;;
status) status ;;
*) die "usage: browser-theme.sh status|setup|setup-zen|install-zen-live|setup-zen-live|doctor-zen-live|setup-brave|apply" ;;
esac
