#!/usr/bin/env python3
"""Read, apply, and persist Niri output settings owned by nbshell."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
from pathlib import Path


CONFIG_HOME = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
STATE_FILE = CONFIG_HOME / "nbshell" / "displays.json"
NIRI_FILE = CONFIG_HOME / "niri" / "nbshell-outputs.kdl"
OUTPUT_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")
MODE_RE = re.compile(r"^(auto|\d+x\d+@\d+(?:\.\d+)?)$")
TRANSFORMS = {"normal", "90", "180", "270", "flipped", "flipped-90", "flipped-180", "flipped-270"}


def niri_json(command: str) -> dict:
    result = subprocess.run(["niri", "msg", "--json", command], text=True, capture_output=True, check=True)
    value = json.loads(result.stdout)
    return value if isinstance(value, dict) else {}


def outputs() -> dict:
    return niri_json("outputs")


def load_state() -> dict:
    try:
        value = json.loads(STATE_FILE.read_text())
        return value if isinstance(value, dict) else {}
    except (OSError, ValueError):
        return {}


def mode_label(mode: dict) -> str:
    refresh = int(mode.get("refresh_rate", 0)) / 1000
    return f"{int(mode.get('width', 0))}x{int(mode.get('height', 0))}@{refresh:.3f}"


def status() -> dict:
    raw = outputs()
    focused = ""
    try:
        focused = str(niri_json("focused-output").get("name") or "")
    except (subprocess.SubprocessError, ValueError):
        pass
    rows = []
    for name, row in raw.items():
        logical = row.get("logical") or {}
        current_index = row.get("current_mode")
        modes = []
        for index, mode in enumerate(row.get("modes") or []):
            modes.append({
                "label": mode_label(mode),
                "width": int(mode.get("width", 0)),
                "height": int(mode.get("height", 0)),
                "refresh": round(int(mode.get("refresh_rate", 0)) / 1000, 3),
                "preferred": bool(mode.get("is_preferred", False)),
                "current": current_index == index,
            })
        rows.append({
            "name": str(name),
            "make": str(row.get("make") or ""),
            "model": str(row.get("model") or ""),
            "enabled": bool(logical),
            "focused": name == focused,
            "x": int(logical.get("x", 0)),
            "y": int(logical.get("y", 0)),
            "width": int(logical.get("width", 0)),
            "height": int(logical.get("height", 0)),
            "scale": float(logical.get("scale", 1)),
            "transform": str(logical.get("transform") or "Normal").lower(),
            "vrrSupported": bool(row.get("vrr_supported", False)),
            "vrrEnabled": bool(row.get("vrr_enabled", False)),
            "modes": modes,
            "currentMode": next((mode["label"] for mode in modes if mode["current"]), ""),
        })
    rows.sort(key=lambda row: (row["x"], row["y"], row["name"]))
    return {"outputs": rows, "saved": load_state()}


def validate_name(name: str) -> None:
    if not OUTPUT_RE.fullmatch(name):
        raise SystemExit(f"Invalid output name: {name}")


def run_output(name: str, *args: str) -> None:
    validate_name(name)
    subprocess.run(["niri", "msg", "output", name, *args], check=True)


def save_state(state: dict) -> None:
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = STATE_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
    tmp.replace(STATE_FILE)
    render_kdl(state)


def render_kdl(state: dict) -> None:
    lines = ["// Generated by nbshell display. Edit through the display panel or CLI."]
    for name in sorted(state):
        validate_name(name)
        row = state[name]
        lines.append(f'output "{name}" {{')
        if row.get("enabled") is False:
            lines.append("    off")
        else:
            if row.get("mode"): lines.append(f'    mode "{row["mode"]}"')
            if row.get("scale") is not None: lines.append(f'    scale {float(row["scale"]):g}')
            if row.get("transform"): lines.append(f'    transform "{row["transform"]}"')
            if row.get("x") is not None and row.get("y") is not None:
                lines.append(f'    position x={int(row["x"])} y={int(row["y"])}')
        lines.append("}")
    NIRI_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = NIRI_FILE.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n")
    tmp.replace(NIRI_FILE)


def update(name: str, key: str, value) -> None:
    state = load_state()
    row = dict(state.get(name) or {})
    row[key] = value
    if key != "enabled": row["enabled"] = True
    state[name] = row
    save_state(state)


def set_value(name: str, key: str, value: str) -> None:
    validate_name(name)
    if key == "mode":
        if not MODE_RE.fullmatch(value): raise SystemExit("Mode must be auto or WIDTHxHEIGHT@HZ")
        run_output(name, "mode", value)
        update(name, "mode", value)
    elif key == "scale":
        scale = float(value)
        if not 0.5 <= scale <= 4: raise SystemExit("Scale must be between 0.5 and 4")
        run_output(name, "scale", f"{scale:g}")
        update(name, "scale", scale)
    elif key == "transform":
        transform = value.lower().replace("normal", "normal")
        if transform not in TRANSFORMS: raise SystemExit("Unsupported transform")
        run_output(name, "transform", transform)
        update(name, "transform", transform)
    elif key == "enabled":
        enabled = value.lower() in {"1", "true", "yes", "on"}
        if not enabled:
            active = [row for row in status()["outputs"] if row["enabled"]]
            if len(active) <= 1: raise SystemExit("Refusing to turn off the only enabled output")
        run_output(name, "on" if enabled else "off")
        update(name, "enabled", enabled)
    else:
        raise SystemExit(f"Unknown property: {key}")


def place(name: str, relation: str, reference: str) -> None:
    if relation == "auto":
        run_output(name, "position", "auto")
        state = load_state(); row = dict(state.get(name) or {}); row.pop("x", None); row.pop("y", None); state[name] = row; save_state(state)
        return
    validate_name(reference)
    rows = {row["name"]: row for row in status()["outputs"]}
    target, anchor = rows.get(name), rows.get(reference)
    if not target or not anchor or not target["enabled"] or not anchor["enabled"]:
        raise SystemExit("Both outputs must be enabled")
    if relation == "left": x, y = anchor["x"] - target["width"], anchor["y"]
    elif relation == "right": x, y = anchor["x"] + anchor["width"], anchor["y"]
    elif relation == "above": x, y = anchor["x"], anchor["y"] - target["height"]
    elif relation == "below": x, y = anchor["x"], anchor["y"] + anchor["height"]
    elif relation == "same": x, y = anchor["x"], anchor["y"]
    else: raise SystemExit("Position must be left, right, above, below, same, or auto")
    run_output(name, "position", "set", str(x), str(y))
    state = load_state(); row = dict(state.get(name) or {}); row.update({"x": x, "y": y, "enabled": True}); state[name] = row; save_state(state)


def main() -> int:
    parser = argparse.ArgumentParser(description="nbshell Niri display control")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("status")
    set_p = sub.add_parser("set"); set_p.add_argument("output"); set_p.add_argument("property", choices=["mode", "scale", "transform", "enabled"]); set_p.add_argument("value")
    place_p = sub.add_parser("place"); place_p.add_argument("output"); place_p.add_argument("relation", choices=["left", "right", "above", "below", "same", "auto"]); place_p.add_argument("reference", nargs="?", default="")
    args = parser.parse_args()
    if args.command == "status": print(json.dumps(status())); return 0
    if args.command == "set": set_value(args.output, args.property, args.value); return 0
    if args.command == "place": place(args.output, args.relation, args.reference); return 0
    return 2


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (subprocess.CalledProcessError, ValueError) as error:
        raise SystemExit(str(error))
