#!/usr/bin/env python3
"""Read, apply, and persist output settings owned by nbshell."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
from pathlib import Path


CONFIG_HOME = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
STATE_FILE = CONFIG_HOME / "nbshell" / "displays.json"
UMBRIEL_FILE = CONFIG_HOME / "umbriel" / "nbshell-outputs.toml"
OUTPUT_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")
MODE_RE = re.compile(r"^(auto|\d+x\d+@\d+(?:\.\d+)?)$")
TRANSFORMS = {"normal", "90", "180", "270", "flipped", "flipped-90", "flipped-180", "flipped-270"}



def load_state() -> dict:
    try:
        value = json.loads(STATE_FILE.read_text())
        return value if isinstance(value, dict) else {}
    except (OSError, ValueError):
        return {}


def mode_label(mode: dict) -> str:
    refresh = int(mode.get("refresh_rate", 0)) / 1000
    return f"{int(mode.get('width', 0))}x{int(mode.get('height', 0))}@{refresh:.3f}"


def status() -> dict:
    result = subprocess.run(["wlr-randr", "--json"], text=True, capture_output=True, check=True)
    focused_output = ""
    try:
        workspaces = subprocess.run(
            ["umbriel", "workspaces", "--json"], text=True, capture_output=True,
            check=True,
        )
        focused_output = str(next(
            (row.get("output") for row in json.loads(workspaces.stdout) if row.get("focused")),
            "",
        ))
    except (subprocess.SubprocessError, ValueError, TypeError):
        pass
    rows = []
    for row in json.loads(result.stdout):
        position = row.get("position") or {}
        modes = [{
            "label": f'{int(mode.get("width", 0))}x{int(mode.get("height", 0))}@{float(mode.get("refresh", 0)):.3f}',
            "width": int(mode.get("width", 0)), "height": int(mode.get("height", 0)),
            "refresh": round(float(mode.get("refresh", 0)), 3),
            "preferred": bool(mode.get("preferred")), "current": bool(mode.get("current")),
        } for mode in row.get("modes") or []]
        rows.append({
            "name": str(row.get("name") or ""), "make": str(row.get("make") or ""),
            "model": str(row.get("model") or ""), "enabled": bool(row.get("enabled")),
            "focused": str(row.get("name") or "") == focused_output,
            "x": int(position.get("x", 0)), "y": int(position.get("y", 0)),
            "width": next((m["width"] for m in modes if m["current"]), 0),
            "height": next((m["height"] for m in modes if m["current"]), 0),
            "scale": float(row.get("scale", 1)), "transform": str(row.get("transform") or "normal"),
            "vrrSupported": True, "vrrEnabled": bool(row.get("adaptive_sync")), "modes": modes,
            "currentMode": next((m["label"] for m in modes if m["current"]), ""),
        })
    rows.sort(key=lambda item: (item["x"], item["y"], item["name"]))
    return {"outputs": rows, "saved": load_state(), "backend": "umbriel"}


def validate_name(name: str) -> None:
    if not OUTPUT_RE.fullmatch(name):
        raise SystemExit(f"Invalid output name: {name}")


def run_output(name: str, *args: str) -> None:
    validate_name(name)
    mapping = {
        "mode": ["--mode"], "scale": ["--scale"], "transform": ["--transform"],
        "on": ["--on"], "off": ["--off"],
    }
    if args[:2] == ("position", "set"):
        options = ["--pos", f"{args[2]},{args[3]}"]
    elif args[:2] == ("position", "auto"):
        raise SystemExit("Automatic placement is not supported by wlr-randr; choose a relative position")
    else:
        options = mapping.get(args[0], []) + list(args[1:])
    if not options: raise SystemExit("Unsupported Umbriel output operation")
    subprocess.run(["wlr-randr", "--output", name, *options], check=True)


def save_state(state: dict) -> None:
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = STATE_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
    tmp.replace(STATE_FILE)
    render_toml(state)


def render_toml(state: dict) -> None:
    lines = ["# Generated by nbshell display. Include from config.toml."]
    for name in sorted(state):
        validate_name(name); row = state[name]
        lines.append(f'\n[output."{name}"]')
        if row.get("enabled") is not None: lines.append(f'enabled = {str(bool(row["enabled"])).lower()}')
        if row.get("mode"): lines.append(f'mode = "{row["mode"]}"')
        if row.get("scale") is not None: lines.append(f'scale = {float(row["scale"]):g}')
        if row.get("transform"): lines.append(f'transform = "{row["transform"]}"')
        if row.get("x") is not None and row.get("y") is not None:
            lines.append(f'position = [{int(row["x"])}, {int(row["y"])}]')
    UMBRIEL_FILE.parent.mkdir(parents=True, exist_ok=True)
    tmp = UMBRIEL_FILE.with_suffix(".tmp"); tmp.write_text("\n".join(lines) + "\n"); tmp.replace(UMBRIEL_FILE)



def update(name: str, key: str, value) -> None:
    state = load_state()
    row = dict(state.get(name) or {})
    row[key] = value
    if key != "enabled": row["enabled"] = True
    state[name] = row
    save_state(state)


def set_umbriel_mode(name: str, value: str) -> None:
    """Apply an Umbriel mode through its config and roll back rejected modes."""
    previous = load_state()
    desired = {output: dict(settings) for output, settings in previous.items()}
    row = dict(desired.get(name) or {})
    row["enabled"] = True
    if value == "auto":
        row.pop("mode", None)
    else:
        row["mode"] = value
    desired[name] = row
    save_state(desired)
    subprocess.run(["umbriel", "msg", "config-reload"], check=True)

    live = next((output for output in status()["outputs"] if output["name"] == name), None)
    accepted = bool(live) and (
        any(mode["current"] and mode["preferred"] for mode in live["modes"])
        if value == "auto" else live["currentMode"] == value
    )
    if accepted:
        return

    save_state(previous)
    subprocess.run(["umbriel", "msg", "config-reload"], check=True)
    raise SystemExit(f"Umbriel rejected mode {value} for {name}; the previous mode was restored")


def set_value(name: str, key: str, value: str) -> None:
    validate_name(name)
    if key == "mode":
        if not MODE_RE.fullmatch(value): raise SystemExit("Mode must be auto or WIDTHxHEIGHT@HZ")
        set_umbriel_mode(name, value)
    elif key == "scale":
        scale = float(value)
        if not 0.5 <= scale <= 4: raise SystemExit("Scale must be between 0.5 and 4")
        run_output(name, "scale", f"{scale:g}")
        update(name, "scale", scale)
    elif key == "transform":
        transform = value.lower().replace("normal", "normal")
        if transform not in TRANSFORMS: raise SystemExit("Unsupported transform")
        run_output(name, "transform", transform)
        update(name, "transform", transform)
    elif key == "enabled":
        enabled = value.lower() in {"1", "true", "yes", "on"}
        if not enabled:
            active = [row for row in status()["outputs"] if row["enabled"]]
            if len(active) <= 1: raise SystemExit("Refusing to turn off the only enabled output")
        update(name, "enabled", enabled)
        subprocess.run(["umbriel", "msg", "config-reload"], check=True)
    else:
        raise SystemExit(f"Unknown property: {key}")


def place(name: str, relation: str, reference: str) -> None:
    if relation == "auto":
        state = load_state(); row = dict(state.get(name) or {}); row.pop("x", None); row.pop("y", None); state[name] = row; save_state(state)
        subprocess.run(["umbriel", "msg", "config-reload"], check=True)
        return
    validate_name(reference)
    rows = {row["name"]: row for row in status()["outputs"]}
    target, anchor = rows.get(name), rows.get(reference)
    if not target or not anchor or not target["enabled"] or not anchor["enabled"]:
        raise SystemExit("Both outputs must be enabled")
    if relation == "left": x, y = anchor["x"] - target["width"], anchor["y"]
    elif relation == "right": x, y = anchor["x"] + anchor["width"], anchor["y"]
    elif relation == "above": x, y = anchor["x"], anchor["y"] - target["height"]
    elif relation == "below": x, y = anchor["x"], anchor["y"] + anchor["height"]
    elif relation == "same": x, y = anchor["x"], anchor["y"]
    else: raise SystemExit("Position must be left, right, above, below, same, or auto")
    if relation != "same":
        # Umbriel normalizes the global output coordinate space. Supplying a
        # calculated absolute --pos can therefore be moved beside the anchor
        # even though the requested topology was above/below it. Let the
        # output-management protocol express the relationship directly.
        relative_flag = {
            "left": "--left-of", "right": "--right-of",
            "above": "--above", "below": "--below",
        }[relation]
        subprocess.run(["wlr-randr", "--output", name, relative_flag, reference], check=True)
    else:
        run_output(name, "position", "set", str(x), str(y))

    # Umbriel may translate every output after a relative move. Persist its
    # authoritative coordinates for all connected outputs, not only the one
    # that was moved, so config reloads reproduce the live topology exactly.
    live_rows = status()["outputs"]
    state = load_state()
    for live in live_rows:
        if not live["enabled"]:
            continue
        row = dict(state.get(live["name"]) or {})
        row.update({"x": live["x"], "y": live["y"], "enabled": True})
        state[live["name"]] = row
    save_state(state)


def main() -> int:
    parser = argparse.ArgumentParser(description="nbshell display control")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("status")
    set_p = sub.add_parser("set"); set_p.add_argument("output"); set_p.add_argument("property", choices=["mode", "scale", "transform", "enabled"]); set_p.add_argument("value")
    place_p = sub.add_parser("place"); place_p.add_argument("output"); place_p.add_argument("relation", choices=["left", "right", "above", "below", "same", "auto"]); place_p.add_argument("reference", nargs="?", default="")
    args = parser.parse_args()
    if args.command == "status": print(json.dumps(status())); return 0
    if args.command == "set": set_value(args.output, args.property, args.value); return 0
    if args.command == "place": place(args.output, args.relation, args.reference); return 0
    return 2


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (subprocess.CalledProcessError, ValueError) as error:
        raise SystemExit(str(error))
