#!/usr/bin/env python3
"""Render public greetd frontend assets from nbshell's current theme."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys

import lockscreen


ORBITAL_ROOT = Path("/usr/local/share/nbshell/greeter")
PUBLIC_WALLPAPER = Path("/usr/local/share/nbshell/greeter-wallpaper.jpg")


def session_entries(home: Path) -> list[dict[str, object]]:
    """Return the root-owned Umbriel login session allowlist."""
    launcher = Path(os.environ.get("NBSHELL_UMBRIEL_LAUNCHER", "/usr/local/bin/start-umbriel"))
    return [{"name": "Umbriel", "command": [str(launcher)]}] if launcher.is_file() and os.access(launcher, os.X_OK) else []


def render(output_dir: Path, username: str, frontend: str) -> Path:
    config = lockscreen.load_json(lockscreen.CONFIG_PATH)
    colors, theme_dir = lockscreen.load_theme(config)
    wallpaper = lockscreen.find_wallpaper(config, theme_dir)
    if wallpaper is None:
        raise SystemExit("nbshell: no readable wallpaper is available for the greeter")

    clean_user = username.strip()
    if not clean_user or any(character in clean_user for character in "\r\n\0"):
        raise SystemExit("nbshell: invalid greeter username")
    sessions = session_entries(Path.home())
    if not sessions:
        raise SystemExit("nbshell: the system Umbriel launcher is unavailable")

    font = str(config.get("font") or "JetBrainsMono Nerd Font").replace("\n", " ").replace("\r", " ")
    font_size = lockscreen.bounded_int(config, "fontSize", 14, 8, 24)
    radius = lockscreen.bounded_int(config, "radius", 2, 0, 40)
    border = lockscreen.bounded_int(config, "borderWidth", 1, 0, 4)
    dim = lockscreen.bounded_int(config, "lockDim", 48, 0, 85) / 100
    background = colors["background"]
    foreground = colors["foreground"]
    muted = colors["muted"]
    accent = colors["accent"]

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "fingerprint.svg").write_text(
        f'''<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 16 16">
<path fill="{accent}" d="m8.074 0c-1.203-.012-2.406.285-3.492.89a1 1 0 1 0 .977 1.747 5 5 0 0 1 7.44 4.363v1a1 1 0 1 0 2 0V7A7 7 0 0 0 8.074 0ZM2.875 2.832a1 1 0 0 0-.82.469A7 7 0 0 0 1 7v5.063a1 1 0 1 0 2 0V7c0-.934.262-1.852.754-2.645a1 1 0 0 0-.879-1.523ZM8 3a4 4 0 0 0-4 4v1a1 1 0 1 0 2 0V7a2 2 0 1 1 4 0v5c0 .617.23 1.91 1.293 2.707a1 1 0 0 0 1.414-1.414C12.325 12.91 12 12.25 12 12V7a4 4 0 0 0-4-4Zm0 3a1 1 0 0 0-1 1v5c0 1.156.277 2.79 1.293 3.707a1 1 0 0 0 1.414-1.414C9.223 13.81 9 12.566 9 12V7a1 1 0 0 0-1-1Zm-3 4a1 1 0 0 0-1 1v3a1 1 0 1 0 2 0v-3a1 1 0 0 0-1-1Zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2Z"/>
</svg>\n''', encoding="utf-8"
    )
    (output_dir / "umbriel.toml").write_text(
        f'''# Generated by nbshell for the isolated greetd frontend session.
[general]
show_cheatsheet = false

[colors]
background = "{background}FF"
text_primary = "{foreground}FF"
text_muted = "{muted}FF"
accent_primary = "{accent}FF"

[layout]
mode = "dwindle"

[input.keyboard]
layout = "de"
numlock_toggle = true

[[window_rule]]
match.app_id = "^dev[.]nerdi[.]nbshell[.]greeter$"
default_focused = true
''', encoding="utf-8"
    )

    orbital_config = {
        "username": clean_user,
        "wallpaper": str(PUBLIC_WALLPAPER),
        "background": background,
        "foreground": foreground,
        "bright": colors["bright"],
        "muted": muted,
        "accent": accent,
        "red": colors["red"],
        "font": font,
        "fontSize": font_size,
        "radius": radius,
        "borderWidth": border,
        "dimOpacity": dim,
        "hourFormat": "12" if str(config.get("lockHourFormat")) == "12" else "24",
        "reducedMotion": str(config.get("motionProfile") or "standard") == "reduced",
        "showSecondsRing": config.get("greeterShowSecondsRing", True) is not False,
        "showPowerActions": config.get("greeterShowPowerActions", True) is not False,
        "autoStartAuthentication": config.get("greeterAutoStartAuthentication", True) is not False,
        "defaultSessionIndex": 0,
        "sessions": sessions,
    }
    (output_dir / "config.json").write_text(
        json.dumps(orbital_config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return wallpaper


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--user", default=os.environ.get("USER", ""))
    parser.add_argument("--frontend", choices=("orbital",), default="orbital")
    args = parser.parse_args()
    print(render(args.output_dir, args.user, args.frontend))
    return 0


if __name__ == "__main__":
    sys.exit(main())
