#!/usr/bin/env python3
"""Render ReGreet assets from the same nbshell state as the session lock."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import lockscreen


def render(output_dir: Path) -> Path:
    config = lockscreen.load_json(lockscreen.CONFIG_PATH)
    colors, theme_dir = lockscreen.load_theme(config)
    wallpaper = lockscreen.find_wallpaper(config, theme_dir)
    if wallpaper is None:
        raise SystemExit("nbshell: no readable wallpaper is available for the greeter")

    font = str(config.get("font") or "JetBrainsMono Nerd Font").replace("\n", " ")
    font_size = lockscreen.bounded_int(config, "fontSize", 14, 8, 24)
    radius = lockscreen.bounded_int(config, "radius", 2, 0, 40)
    border = lockscreen.bounded_int(config, "borderWidth", 1, 0, 4)
    background = colors["background"]
    foreground = colors["foreground"]
    muted = colors["muted"]
    accent = colors["accent"]

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "fingerprint.svg").write_text(
        f'''<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 16 16">
<path fill="{accent}" d="m8.074 0c-1.203-.012-2.406.285-3.492.89a1 1 0 1 0 .977 1.747 5 5 0 0 1 7.44 4.363v1a1 1 0 1 0 2 0V7A7 7 0 0 0 8.074 0ZM2.875 2.832a1 1 0 0 0-.82.469A7 7 0 0 0 1 7v5.063a1 1 0 1 0 2 0V7c0-.934.262-1.852.754-2.645a1 1 0 0 0-.879-1.523ZM8 3a4 4 0 0 0-4 4v1a1 1 0 1 0 2 0V7a2 2 0 1 1 4 0v5c0 .617.23 1.91 1.293 2.707a1 1 0 0 0 1.414-1.414C12.325 12.91 12 12.25 12 12V7a4 4 0 0 0-4-4Zm0 3a1 1 0 0 0-1 1v5c0 1.156.277 2.79 1.293 3.707a1 1 0 0 0 1.414-1.414C9.223 13.81 9 12.566 9 12V7a1 1 0 0 0-1-1Zm-3 4a1 1 0 0 0-1 1v3a1 1 0 1 0 2 0v-3a1 1 0 0 0-1-1Zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2Z"/>
</svg>\n''', encoding="utf-8"
    )
    (output_dir / "regreet.css").write_text(
        f'''/* Generated by nbshell. Authentication remains with greetd/ReGreet. */
* {{
  font-family: "{font}", monospace;
  font-size: {font_size}px;
  color: {foreground};
}}

window, overlay {{ background-color: {background}; }}
picture {{ filter: brightness(0.52) saturate(0.82); }}

overlay > frame.background:nth-child(2) {{
  min-width: 620px;
  min-height: 352px;
  background-color: {background};
  border: {border}px solid {accent};
  border-radius: {radius}px;
  box-shadow: 0 18px 48px rgba(0, 0, 0, 0.55);
  padding: 18px;
}}

overlay > frame.background:nth-child(3) {{
  min-width: 0;
  min-height: 0;
  background: transparent;
  border: 0;
  border-radius: 0;
  box-shadow: none;
  padding: 26px;
}}

overlay > frame.background:nth-child(3) label {{
  font-size: 48px;
  font-weight: 500;
  color: {colors['bright']};
}}

entry, combobox button {{
  min-height: 42px;
  background: {background};
  color: {foreground};
  border: {border}px solid {muted};
  border-radius: {radius}px;
  box-shadow: none;
}}
passwordentry entry {{
  background-image: url("/usr/local/share/nbshell/fingerprint.svg");
  background-repeat: no-repeat;
  background-position: right center;
  padding-right: 42px;
}}
entry:focus, combobox button:focus {{ border-color: {accent}; outline-color: {accent}; }}

button {{
  min-height: 36px;
  background: {background};
  color: {foreground};
  border: {border}px solid {muted};
  border-radius: {radius}px;
  box-shadow: none;
}}
button:hover, button:focus {{ border-color: {accent}; }}
button.suggested-action {{ background: {accent}; color: {background}; border-color: {accent}; }}
button.destructive-action {{ color: {colors['red']}; border-color: {colors['red']}; }}
popover, menu {{
  background: {background}; color: {foreground};
  border: {border}px solid {accent}; border-radius: {radius}px;
}}
selection {{ background: {accent}; color: {background}; }}
''', encoding="utf-8"
    )
    (output_dir / "niri.kdl").write_text(
        f'''// Generated by nbshell for the isolated ReGreet session.
spawn-sh-at-startup "regreet; niri msg action quit --skip-confirmation"
hotkey-overlay {{
    skip-at-startup
}}
environment {{
    XDG_SESSION_TYPE "wayland"
    XDG_CURRENT_DESKTOP "nbshell-greeter"
}}
input {{
    keyboard {{
        xkb {{
            layout "de"
        }}
        numlock
    }}
    touchpad {{
        tap
    }}
}}
cursor {{
    xcursor-theme "Adwaita"
    xcursor-size 24
}}
layout {{
    background-color "{background}"
}}
window-rule {{
    match app-id="regreet"
    open-maximized true
}}
debug {{
    honor-xdg-activation-with-invalid-serial
}}
''', encoding="utf-8"
    )
    return wallpaper


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output_dir", type=Path)
    args = parser.parse_args()
    print(render(args.output_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
