#!/usr/bin/env python3
"""Render ReGreet assets from the same nbshell state as the session lock."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import lockscreen


def render(output_dir: Path) -> Path:
    config = lockscreen.load_json(lockscreen.CONFIG_PATH)
    colors, theme_dir = lockscreen.load_theme(config)
    wallpaper = lockscreen.find_wallpaper(config, theme_dir)
    if wallpaper is None:
        raise SystemExit("nbshell: no readable wallpaper is available for the greeter")

    font = str(config.get("font") or "JetBrainsMono Nerd Font").replace("\n", " ")
    font_size = lockscreen.bounded_int(config, "fontSize", 14, 8, 24)
    radius = lockscreen.bounded_int(config, "radius", 2, 0, 40)
    border = lockscreen.bounded_int(config, "borderWidth", 1, 0, 4)
    background = colors["background"]
    foreground = colors["foreground"]
    muted = colors["muted"]
    accent = colors["accent"]

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "regreet.css").write_text(
        f'''/* Generated by nbshell. Authentication remains with greetd/ReGreet. */
* {{
  font-family: "{font}", monospace;
  font-size: {font_size}px;
  color: {foreground};
}}

window, overlay {{ background-color: {background}; }}
picture {{ filter: brightness(0.52) saturate(0.82); }}

frame.background {{
  min-width: 620px;
  background-color: {background};
  border: {border}px solid {accent};
  border-radius: {radius}px;
  box-shadow: 0 18px 48px rgba(0, 0, 0, 0.55);
  padding: 18px;
}}

entry, combobox button {{
  min-height: 42px;
  background: {background};
  color: {foreground};
  border: {border}px solid {muted};
  border-radius: {radius}px;
  box-shadow: none;
}}
entry:focus, combobox button:focus {{ border-color: {accent}; outline-color: {accent}; }}

button {{
  min-height: 36px;
  background: {background};
  color: {foreground};
  border: {border}px solid {muted};
  border-radius: {radius}px;
  box-shadow: none;
}}
button:hover, button:focus {{ border-color: {accent}; }}
button.suggested-action {{ background: {accent}; color: {background}; border-color: {accent}; }}
button.destructive-action {{ color: {colors['red']}; border-color: {colors['red']}; }}
popover, menu {{
  background: {background}; color: {foreground};
  border: {border}px solid {accent}; border-radius: {radius}px;
}}
selection {{ background: {accent}; color: {background}; }}
''', encoding="utf-8"
    )
    (output_dir / "niri.kdl").write_text(
        f'''// Generated by nbshell for the isolated ReGreet session.
spawn-sh-at-startup "regreet; niri msg action quit --skip-confirmation"
hotkey-overlay {{
    skip-at-startup
}}
environment {{
    XDG_SESSION_TYPE "wayland"
    XDG_CURRENT_DESKTOP "nbshell-greeter"
}}
input {{
    keyboard {{
        xkb {{
            layout "de"
        }}
        numlock
    }}
    touchpad {{
        tap
    }}
}}
cursor {{
    xcursor-theme "Adwaita"
    xcursor-size 24
}}
layout {{
    background-color "{background}"
}}
window-rule {{
    match app-id="regreet"
    open-maximized true
}}
debug {{
    honor-xdg-activation-with-invalid-serial
}}
''', encoding="utf-8"
    )
    return wallpaper


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output_dir", type=Path)
    args = parser.parse_args()
    print(render(args.output_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
